version: "3.1"

services:
  webapp:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8123:80
    environment:
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DEBUG: 1
      ABSPATH: /usr/src/wordpress/
  wordpress:
    image: wordpress
    ports:
      - 8158:80
    environment:
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DEBUG: 1
      ABSPATH: /usr/src/wordpress/
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/isoblock
  cli:
    image: wordpress:cli
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/isoblock
    environment:
      WORDPRESS_DB_PASSWORD: example
      ABSPATH: /usr/src/wordpress/
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress_test

  wordpress_phpunit:
    image: chriszarate/wordpress-phpunit
    environment:
      PHPUNIT_DB_HOST: mysql
    volumes:
      - .:/app
      - testsuite:/tmp

  composer:
    image: composer
    volumes:
      - .:/app

volumes:
  testsuite:
  wordpress:
